source 'https://rubygems.org'
gem 'asciidoctor', '~> 1.5.6'
gem 'tilt', '2.0'
gem 'thread_safe', '~> 0.3'
gem 'haml', '~> 5.0'
gem 'asciidoctor-diagram', '1.5'
gem 'rake', '~> 10.5'
gem 'html-proofer', '~> 3.8'
